<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Persistence\Model\PommIssue\PommSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Country
 *
 * Structure class for relation pomm.country.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Country extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('pomm.country')
            ->setPrimaryKey(['country_id'])
            ->addField('country_id', 'int4')
            ->addField('name', 'varchar')
            ;
    }
}
